# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Angel\Documents\github\moti\ui\consulta_leve_este_mes.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(627, 395)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.cs_diagnostico = QtWidgets.QLineEdit(self.widget)
        self.cs_diagnostico.setObjectName("cs_diagnostico")
        self.gridLayout.addWidget(self.cs_diagnostico, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.tabla_consulta = QtWidgets.QTableWidget(Form)
        self.tabla_consulta.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_consulta.setObjectName("tabla_consulta")
        self.tabla_consulta.setColumnCount(0)
        self.tabla_consulta.setRowCount(0)
        self.verticalLayout.addWidget(self.tabla_consulta)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_accion = QtWidgets.QPushButton(self.widget_2)
        self.btn_accion.setObjectName("btn_accion")
        self.horizontalLayout.addWidget(self.btn_accion)
        self.btn_cerrar = QtWidgets.QPushButton(self.widget_2)
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout.addWidget(self.btn_cerrar)
        self.verticalLayout.addWidget(self.widget_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.tabla_consulta, self.btn_accion)
        Form.setTabOrder(self.btn_accion, self.btn_cerrar)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Consultas Leves este mes segun diagnositico ordenadas por la fecha"))
        self.label_5.setText(_translate("Form", "Diagnostico"))
        self.tabla_consulta.setSortingEnabled(True)
        self.btn_accion.setText(_translate("Form", "Buscar"))
        self.btn_cerrar.setText(_translate("Form", "Cerrar"))
