# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Angel\Documents\github\moti\ui\tiempo_promedio.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(359, 103)
        Dialog.setMinimumSize(QtCore.QSize(359, 103))
        Dialog.setMaximumSize(QtCore.QSize(359, 103))
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_texto = QtWidgets.QLabel(self.widget)
        self.label_texto.setObjectName("label_texto")
        self.gridLayout.addWidget(self.label_texto, 0, 0, 1, 1)
        self.a_codigo = QtWidgets.QLineEdit(self.widget)
        self.a_codigo.setObjectName("a_codigo")
        self.gridLayout.addWidget(self.a_codigo, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_accion = QtWidgets.QPushButton(self.widget_2)
        self.btn_accion.setObjectName("btn_accion")
        self.horizontalLayout.addWidget(self.btn_accion)
        self.btn_cancelar = QtWidgets.QPushButton(self.widget_2)
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.horizontalLayout.addWidget(self.btn_cancelar)
        self.verticalLayout.addWidget(self.widget_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Tiempo Promedio segun codigo Consulta"))
        self.label_texto.setText(_translate("Dialog", "Codigo"))
        self.btn_accion.setText(_translate("Dialog", "Calcular Tiempo Promedio"))
        self.btn_cancelar.setText(_translate("Dialog", "Cancelar"))
