# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Angel\Documents\github\moti\ui\ventana_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(639, 491)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 639, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuCRUD = QtWidgets.QMenu(self.menubar)
        self.menuCRUD.setObjectName("menuCRUD")
        self.menuOperaciones = QtWidgets.QMenu(self.menubar)
        self.menuOperaciones.setObjectName("menuOperaciones")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.opc_salir = QtWidgets.QAction(MainWindow)
        self.opc_salir.setObjectName("opc_salir")
        self.opc_acerca = QtWidgets.QAction(MainWindow)
        self.opc_acerca.setObjectName("opc_acerca")
        self.actionPaciente_Leve = QtWidgets.QAction(MainWindow)
        self.actionPaciente_Leve.setObjectName("actionPaciente_Leve")
        self.actionConsultaUrgencia = QtWidgets.QAction(MainWindow)
        self.actionConsultaUrgencia.setObjectName("actionConsultaUrgencia")
        self.actionDoctor = QtWidgets.QAction(MainWindow)
        self.actionDoctor.setObjectName("actionDoctor")
        self.actionConsultaLeve = QtWidgets.QAction(MainWindow)
        self.actionConsultaLeve.setObjectName("actionConsultaLeve")
        self.actionPaciente = QtWidgets.QAction(MainWindow)
        self.actionPaciente.setObjectName("actionPaciente")
        self.actionCalcular_Tiempo_Promedio = QtWidgets.QAction(MainWindow)
        self.actionCalcular_Tiempo_Promedio.setObjectName("actionCalcular_Tiempo_Promedio")
        self.actionSignos_Vitales_segun_fecha_Consulta_y_CI_Paciente = QtWidgets.QAction(MainWindow)
        self.actionSignos_Vitales_segun_fecha_Consulta_y_CI_Paciente.setObjectName("actionSignos_Vitales_segun_fecha_Consulta_y_CI_Paciente")
        self.actionConsultas_Urgencia_con_Pacientes_con_Presion_Alta = QtWidgets.QAction(MainWindow)
        self.actionConsultas_Urgencia_con_Pacientes_con_Presion_Alta.setObjectName("actionConsultas_Urgencia_con_Pacientes_con_Presion_Alta")
        self.actionPaciente_de_Mayor_Edad_en_las_Consultas_Leves = QtWidgets.QAction(MainWindow)
        self.actionPaciente_de_Mayor_Edad_en_las_Consultas_Leves.setObjectName("actionPaciente_de_Mayor_Edad_en_las_Consultas_Leves")
        self.actionConsulta_Leves_este_mes_segun_diagnostico = QtWidgets.QAction(MainWindow)
        self.actionConsulta_Leves_este_mes_segun_diagnostico.setObjectName("actionConsulta_Leves_este_mes_segun_diagnostico")
        self.menuArchivo.addAction(self.opc_salir)
        self.menuCRUD.addAction(self.actionPaciente)
        self.menuCRUD.addAction(self.actionDoctor)
        self.menuCRUD.addAction(self.actionConsultaLeve)
        self.menuCRUD.addAction(self.actionConsultaUrgencia)
        self.menuOperaciones.addAction(self.actionCalcular_Tiempo_Promedio)
        self.menuOperaciones.addAction(self.actionSignos_Vitales_segun_fecha_Consulta_y_CI_Paciente)
        self.menuOperaciones.addAction(self.actionConsultas_Urgencia_con_Pacientes_con_Presion_Alta)
        self.menuOperaciones.addAction(self.actionPaciente_de_Mayor_Edad_en_las_Consultas_Leves)
        self.menuOperaciones.addAction(self.actionConsulta_Leves_este_mes_segun_diagnostico)
        self.menuAyuda.addAction(self.opc_acerca)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuCRUD.menuAction())
        self.menubar.addAction(self.menuOperaciones.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SGCH-Sistema de Gestion de Consultas de Hospitales"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuCRUD.setTitle(_translate("MainWindow", "CRUD"))
        self.menuOperaciones.setTitle(_translate("MainWindow", "Operaciones"))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda"))
        self.opc_salir.setText(_translate("MainWindow", "Salir"))
        self.opc_salir.setShortcut(_translate("MainWindow", "Alt+X"))
        self.opc_acerca.setText(_translate("MainWindow", "Acerca de"))
        self.opc_acerca.setShortcut(_translate("MainWindow", "Alt+A"))
        self.actionPaciente_Leve.setText(_translate("MainWindow", "Paciente"))
        self.actionConsultaUrgencia.setText(_translate("MainWindow", "Consulta Urgencia"))
        self.actionDoctor.setText(_translate("MainWindow", "Doctor"))
        self.actionConsultaLeve.setText(_translate("MainWindow", "Consulta Leve"))
        self.actionPaciente.setText(_translate("MainWindow", "Paciente"))
        self.actionCalcular_Tiempo_Promedio.setText(_translate("MainWindow", "Calcular Tiempo Promedio"))
        self.actionSignos_Vitales_segun_fecha_Consulta_y_CI_Paciente.setText(_translate("MainWindow", "Signos Vitales segun fecha Consulta y CI Paciente"))
        self.actionConsultas_Urgencia_con_Pacientes_con_Presion_Alta.setText(_translate("MainWindow", "Porciento Consultas Urgencia con Pacientes con Presion Alta"))
        self.actionPaciente_de_Mayor_Edad_en_las_Consultas_Leves.setText(_translate("MainWindow", "Paciente de Mayor Edad en las Consultas Leves"))
        self.actionConsulta_Leves_este_mes_segun_diagnostico.setText(_translate("MainWindow", "Consulta Leves este mes segun diagnostico"))
